#!/bin/bash
# =============================================================================
# generateLocalRegistryValues.sh
#
# Generates a Helm values override that points child chart repositories and
# third-party image references to a local OCI/container registry.
#
# Usage:
#   ./generateLocalRegistryValues.sh docker-registry:5001 > local-registry-values.yaml
# =============================================================================
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=generatePrivateEcrValues.sh
. "$script_dir/generatePrivateEcrValues.sh"

generate_local_registry_values() {
  local registry="$1"

  generate_private_ecr_values "$registry" | awk -v registry="$registry" '
    /^# Generated by/ {
      print "# Generated by generateLocalRegistryValues.sh"
      next
    }
    /^# ECR Registry:/ {
      print "# Local Registry: " registry
      next
    }
    /^# --- ECR auth/ {
      skip_ecr_auth = 1
      next
    }
    skip_ecr_auth && /^# --- Chart repositories/ {
      skip_ecr_auth = 0
      sub(/ECR/, "local registry")
      print
      next
    }
    skip_ecr_auth {
      next
    }
    {
      print
      if ($0 ~ /^[[:space:]]+repository: "oci:\/\//) {
        indent = $0
        sub(/repository:.*/, "", indent)
        print indent "plainHttp: true"
      }
    }
  '
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  registry="${1:-}"
  if [ -z "$registry" ]; then
    echo "Usage: $0 <local-registry-host> > local-registry-values.yaml" >&2
    exit 1
  fi
  generate_local_registry_values "$registry"
fi
